---
- hosts: all
  become: true

  pre_tasks:
    - name: vars
      include_vars: vars.yml

  tasks:
    - name: install packages
      import_tasks: tasks/packages.yml

    - name: Install Omada
      import_tasks: tasks/omada.yml
