---

- name: apt cache update & upgrade
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full

- name: apt install packages
  apt:
    name:
      - mongodb
      - jsvc
      - curl
      - openjdk-8-jre-headless
    state: present
    cache_valid_time: 3600

- name: Ensure mongo is runnig.
  service:
    name: mongodb
    state: started
    enabled: true

- name: is Omada installed
  command: which tpeap
  failed_when: false
  changed_when: false
  check_mode: false
  register: omada_preset
